### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by joum** [JoshuaWise/integer#1]
I'm trying out your better-sqlite3 package, but I'm not able to install it.

I've tracked it down to this dependency on the `integer` package. Whenever I `npm install --save integer` I get the following output (edited the node project path):

>  CXX(target) Release/obj.target/integer/src/integer.o
  SOLINK_MODULE(target) Release/obj.target/integer.node
  COPY Release/integer.node
cp: preserving permissions for ‘Release/integer.node’: Operation not permitted
integer.target.mk:133: recipe for target 'Release/integer.node' failed
make: *** [Release/integer.node] Error 1
make: Leaving directory '/[node_project_dir]/node_modules/integer/build'

I'm using Ubuntu 16.04 with Node v6.11.4 and NPM 3.10.10.

I already checked and installed node-gyp and build-essentials, so I think I have all the requirements accounted for.

Do you have any insight you could share?

**Comment by joum** [comment]
Also tried updating both `nodejs` and `npm` to no avail. But now there is a different error:

> gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/better-sqlite3/node_modules/integer/build'
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/better-sqlite3/node_modules/integer
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.1 install: `node tools/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


Any help would be very welcome.

**Comment by joum** [comment]
Apparently, this may be related to how `node-gyp` uses `cp -af` and it not working correctly on NFS-based Vagrant boxes (my use case) - [https://github.com/nodejs/node-gyp/issues/562](https://github.com/nodejs/node-gyp/issues/562). 

Sorry to have polluted your issue queue. :)

**Comment by JoshuaWise** [comment]
I just looked at my email notifications to see this thread and thought to myself "whoever said issues don't just resolve themselves..."
