### ISSUE TITLE
Fails to build and install on Linux Debian 9 64bit ( Distro MX Linux )

### ISSUE THREAD

**Issue by drsskelkar** [JoshuaWise/integer#18]
I tried to install npm plugin integer globally with following command.
sudo npm install -g integer.
The module failed to install with error stack Error: integer@2.1.0 install: `node-gyp rebuild`
I am attaching the log file for reference 
Thanks and regards
Sharad Kelkar
[integer-install-error.log](https://github.com/JoshuaWise/integer/files/3377897/integer-install-error.log)

**Comment by cekvenich** [comment]
Let me know if this fixes it, before the install: npm i -g node-gyp@latest

**Comment by JoshuaWise** [comment]
This should be fixed with `integer 3.0.0` due to the use of prebuilt binaries.
