### ISSUE TITLE
error: no matching function for call to ‘v8::String::Value::Value(v8::Local<v8::String>&)’

### ISSUE THREAD

**Issue by jasonkhanlar** [JoshuaWise/integer#20]
Running `npm update` on a fresh new directory environment with no node_modules directory, the installation process fails with this package "integer"

http://dpaste.com/0W1DXY3

I recently updated my ArchLinux system environment to now using npm v6.10.2 and node v12.9.0

Here is my package.json file: http://dpaste.com/3B376PF.txt

**Comment by zangornjak** [comment]
This should be resolved with `node-gyp` updated. Can you try again and update this issue?

**Comment by JoshuaWise** [comment]
closing in favor of https://github.com/JoshuaWise/integer/issues/24
