### ISSUE TITLE
Better-sqlite3 installation failed

### ISSUE THREAD

**Issue by ghost** [JoshuaWise/integer#27]
`root@v1770:/home/jackal# npm install --save better-sqlite3

> integer@3.0.1 install /home/node_modules/integer
> prebuild-install || npm run build-release

prebuild-install WARN install No prebuilt binaries found (target=13.11.0 runtime=node arch=x64 libc= platform=linux)

> integer@3.0.1 build-release /home/node_modules/integer
> node-gyp rebuild --release

make: Entering directory '/home/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
In file included from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/root/.cache/node-gyp/13.11.0/include/node/node.h:618:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  618 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/root/.cache/node-gyp/13.11.0/include/node/node.h:652:3: note: in expansion of macro ‘NODE_MODULE_X’
  652 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/integer.cpp:408:1: note: in expansion of macro ‘NODE_MODULE’
  408 | NODE_MODULE(integer, Integer::Init);
      | ^~~~~~~~~~~
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [integer.target.mk:114: Release/obj.target/integer/src/integer.o] Error 1
make: Leaving directory '/home/node_modules/integer/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-24-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/node_modules/integer
gyp ERR! node -v v13.11.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@3.0.1 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@3.0.1 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-25T17_50_47_234Z-debug.log
npm WARN enmap@5.2.4 requires a peer of better-sqlite3@^5.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN home No description
npm WARN home No repository field.
npm WARN home No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@3.0.1 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-25T17_50_47_492Z-debug.log`

Can't install better-sqlite3

**Comment by JoshuaWise** [comment]
Looks like something on your computer killed the compiler process:
```
g++: fatal error: Killed signal terminated program cc1plus
```

Could be anti-virus software, or something else. It doesn't look like an issue with `better-sqlite3` or `integer`.
