### ISSUE TITLE
Module broken in nodejs v12

### ISSUE THREAD

**Issue by Sasiko** [JoshuaWise/integer#29]
The bot that using integer in nodejs v10 was working fine but when i upgraded to nodejs v12 i couldnt install the proper module. 
I made sure to delete node_modules before i executed npm install

Centos 7
https://i.imgur.com/77ZUFNm.png

**Comment by Sasiko** [comment]
deleting /home/sasiko/.cache/node-gyp/ does not work even if i tried deleting that folder

**Comment by JoshuaWise** [comment]
You're using a very old version of this module. Upgrade to version 4.0.0

**Comment by Sasiko** [comment]
the issue is that its trying to install lower version

make: Leaving directory `/home/sasiko/ar/node_modules/integer/build'
+ integer@4.0.

but when i try to install quick.db or anything, it still forcibly check at version 1 and not above

**Comment by Sasiko** [comment]
Quick.db are referring me this is a inherit issue with integer

 npm i quick.db

> integer@1.0.7 install /home/sasiko/ar/node_modules/quick.db/node_modules/integer
> node-gyp rebuild

make: Entering directory `/home/sasiko/ar/node_modules/quick.db/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
../src/integer.cpp: In static member function ‘static Result Integer::Cast(v8::Local<v8::String>, uint8_t)’:
../src/integer.cpp:329:33: error: no matching function for call to ‘v8::String::Value::Value(v8::Local<v8::String>&)’
   v8::String::Value utf16(string);
                                 ^
../src/integer.cpp:329:33: note: candidate is:
In file included from /home/sasiko/.cache/node-gyp/12.16.3/include/node/node.h:67:0,
                 from ../src/integer.hpp:3,
                 from ../src/integer.cpp:1:
/home/sasiko/.cache/node-gyp/12.16.3/include/node/v8.h:3158:5: note: v8::String::Value::Value(v8::Isolate*, v8::Local<v8::Value>)
     Value(Isolate* isolate, Local<v8::Value> obj);
     ^
/home/sasiko/.cache/node-gyp/12.16.3/include/node/v8.h:3158:5: note:   candidate expects 2 arguments, 1 provided
make: *** [Release/obj.target/integer/src/integer.o] Error 1
make: Leaving directory `/home/sasiko/ar/node_modules/quick.db/node_modules/integer/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.5.10-1.el7.elrepo.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sasiko/ar/node_modules/quick.db/node_modules/integer
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sasiko/.npm/_logs/2020-05-18T11_02_23_849Z-debug.log

**Comment by JoshuaWise** [comment]
@maidos Integer v1.0.7 is no longer supported, so quick.db needs to upgrade their dependencies.
