### ISSUE TITLE
npm ERR! Failed at the integer@1.0.3 install script.

### ISSUE THREAD

**Issue by lieuweberg** [JoshuaWise/integer#5]
* **Node.js Version**: 8.11.2
* **OS**: Ubuntu 16.04.4 x64
* **Module (and version) (if relevant)**: quick.db@6.3.1 // integer@1.0.3

So I get the error `npm ERR! Failed at the integer@1.0.3 install script.` when installing quick.db. This happens to other packages rarely. This is not quick.db's fault though.

On Windows, this can be fixed with `npm -g --add-python-to-path install windows-build-tools node-gyp`, but since I'm on Ubuntu (VPS) I cannot. Does someone know the answer?

This is my debug:
[2018-06-01T19_31_52_541Z-debug.log](https://github.com/nodejs/help/files/2063950/2018-06-01T19_31_52_541Z-debug.log)

**Comment by JoshuaWise** [comment]
This should be fixed in `v1.0.5`
