### ISSUE TITLE
Unable to install integer

### ISSUE THREAD

**Issue by SylverBean** [JoshuaWise/integer#7]
PS G:\Bot> npm i integer

> integer@1.0.5 install G:\Bot\node_modules\integer
> node-gyp rebuild

G:\Bot\node_modules\integer>if not defined npm_config_node_gyp (node "G:\Node.js files\node_modules\npm\node_modules\npm
-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "G:\Node.js files\node_modul
es\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): err
or MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK ve
rsion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [G:\Bot\node_m
odules\integer\build\integer.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (G:\Node.js files\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "G:\\Node.js files\\node.exe" "G:\\Node.js files\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-
gyp.js" "rebuild"
gyp ERR! cwd G:\Bot\node_modules\integer
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencie
s yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer de
pendencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies
 yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencie
s yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yo
urself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dep
endencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies your
self.
npm WARN Bot@1.0.0 No description
npm WARN Bot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! integer@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the integer@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vampy\AppData\Roaming\npm-cache\_logs\2018-07-20T00_40_25_861Z-debug.log

So ... I'm not quite sure whats going wrong here but this is only happening when I try to intstall Integer. It's been happening for a few months now and no one knows how to help me ...

PS C:\windows\system32> npm -v
5.6.0
PS C:\windows\system32> node -v
v8.11.2

**Comment by seangenabe** [comment]
Seems like you don't have the Windows SDK installed. Follow the [instructions for installing node-gyp prerequisites on Windows](https://github.com/nodejs/node-gyp#on-windows).

**Comment by JoshuaWise** [comment]
As @seangenabe pointed out, this is not an issue with `integer`. It's either an issue with your system or with [`node-gyp`](https://github.com/nodejs/node-gyp).
