### ISSUE TITLE
provide binaries to avoid build on install

### ISSUE THREAD

**Issue by oupala** [JoshuaWise/integer#8]
It could be great if this module could provide binaries to avoid build on install, such as node-sass does.

```npm
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /home/user/dev/myproject/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/user/.npm/node-sass/4.9.3/linux-x64-57_binding.node
```

Most issues of integer are about difficulties to install it, this could solve this frequent problem.

Here are the binaries that should be provided:

- Windows
- Unix and Linux
- macOS
- Alpine Linux

For other architectures, there is still node-gyp.

**Comment by MattIPv4** [comment]
This would fix #16

**Comment by prawnsalad** [comment]
Just noting this here as it's the same problem / improvement, https://github.com/JoshuaWise/better-sqlite3/pull/163

**Comment by danielbarela** [comment]
I have created a pull request to do this: https://github.com/JoshuaWise/integer/pull/23

**Comment by cekvenich** [comment]
Let me know if this fixes it, before the install: npm i -g node-gyp@latest

**Comment by oupala** [comment]
This issue is about removing the need of building `integer`. The proposal of @cekvenich to install `node-gyp` is about building `integer`. This is a workaround but does not help to solve the issue.

**Comment by cekvenich** [comment]
@oupala I'm not a maintainer here but I'm sure a PR is welcome.

**Comment by danielbarela** [comment]
@cekvenich  Pull request #23 which fixes this issue has already been merged.

**Comment by JoshuaWise** [comment]
This is now supported with `integer 3.0.0`.

**Comment by oupala** [comment]
It should be clearly written that prebuilt binary are only available for x64.

And yes, x86 is still used nowadays.
